name: Build
on:
  push:
    paths-ignore:
    - 'README.md'
  pull_request:
    paths-ignore:
    - 'README.md'
jobs:
  linux:
    strategy:
      matrix:
        arch: [ x86_64, aarch64 ]
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      if: ${{ matrix.arch != 'x86_64' }}
      run: sudo apt -y update && sudo apt -y install qemu-user-static binfmt-support
    
    - name: Run Docker container
      run: docker run -v "${{ github.workspace }}:/vanilla" itsmattkc/vanilla-u-build:${{ matrix.arch }}-latest
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Vanilla U (${{ matrix.arch }})
        path: ${{ github.workspace }}/Vanilla_U-${{ matrix.arch }}.tar.gz
      
